### ISSUE TITLE
Adding actions and configuring permissions

### ISSUE THREAD

**Issue by renan061** [cartesi/tx-manager#1]
We need to configure actions in this repo as it was configured for the private repo.
(This includes adding the secrets.)

Also, I don't think the main branch is protected from non-PR merges.

**Comment by gligneul** [comment]
@tuler could you help us set up the permissions or give us admin?

**Comment by tuler** [comment]
Are you keeping the `develop` branch in addition to `main`?
What is the default branch of the repo, `develop` or `main`?

**Comment by gligneul** [comment]
I'd rather remove `develop` and only use `main`. Do we have any plans for the other repos?

**Comment by tuler** [comment]
I think it can be left for the team to decide for now.
In "my" repos I'm planning to have `main` as default and eventually a `next` branch. No `develop`.
GitHub uses the default branch as "landing page" for the repo, and also for the default base branch of new PRs.

**Comment by gligneul** [comment]
> In "my" repos I'm planning to have main as default and eventually a next branch. No develop.

I would like to follow the same approach.

**Comment by tuler** [comment]
Actions are enabled, branch protection to `main` configured, and secrets were already configured.
Let me know when I can archive the other private repo.

**Comment by gligneul** [comment]
@tuler you can archive the private repo.
